env:
  browser: true
  es2021: true
overrides:
  - files:
      - '*.svelte'
    parser: svelte-eslint-parser
extends: 
  - eslint:recommended
  - plugin:svelte/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  semi: 
    - error
  indent: 
    - error
    - 4
  svelte/indent: 
    - error
    - indent: 4